import java.util.Scanner;
public class exceptionhandling{
    
    public static void main(String args[]){
        Scanner sc=new Scanner(System.in);
        try{
        int num1,num2,result;
        System.out.println("enter first number");
        num1=sc.nextInt();
         System.out.println("enter second number");
        num2=sc.nextInt();
        result=num1/num2;
         System.out.println("DIVISION:"+result);
         int a[]=new int[5];
         a[7]=66;
        }
        catch(ArithmeticException e){
             System.out.println("DENOMINATOR IS ZERO"+e);
      
        }
        catch(NumberFormatException e){
             System.out.println("INPUT IS WRONG"+e);
        }
        catch(ArrayIndexOutOfBoundsException e){
             System.out.println("ArrayIndexOutOfBoundsException");
        }
        
    }
}
